/*
 * This file has been automatically generated by the ooeclipse integration.
 * http://cedric.bosdonnat.free.fr/ooeclipseintegration
 *
 * Copyright (C) 2009 Novell Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * http://www.gnu.org/copyleft/lesser.html
 */
#include <iostream>

#include "connection.hxx"

using namespace unoclienthelper;
using namespace com::sun::star::uno;

int main( int argc, char** argv )
'{'
	int bRet = 1;

	{0}
	if ( cnx.connect() )
	'{'
		Reference< XComponentContext > xCtx = cnx.getContext();

		// TODO Use the UNO Context here

		cnx.disconnect();
		bRet = 0;
	}

	return bRet;
}
