This project has been automatically generated by the OOEclipse plugins. 

The code contained by this project has been developed by Mirko Nasato and
is part of the JODConverter (http://www.artofsolving.com/opensource/jodconverter).

Copyright (C) 2004-2007 - Mirko Nasato <mirko@artofsolving.com> 